const data = [
  {
    id: 101,
    name: "Panadol",
    price: 24,
    desc: "Panadol contains Paracetamol, used as a pain reliever and fever reducer for headaches, toothaches, fever, and muscle pain.",
    image: "/Products/panadol.jpeg",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 3,
    topProduct: true,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 102,
    name: "Paramol",
    price: 20,
    desc: "Paramol is used to relieve pain, reduce fever, and treat cold and flu symptoms.",
    image: "/Products/paramol.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 103,
    name: "Cataflam",
    price: 38,
    desc: "Cataflam contains Diclofenac Potassium, used to treat toothaches, joint pain, headaches, and menstrual pain.",
    image: "/Products/cataflam.jpeg",
    isStrip: true,
    pieces: 20,
    topProduct: true,
    stripsPerBox: 4,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 104,
    name: "Brufen",
    price: 27,
    desc: "Brufen contains Ibuprofen, a pain reliever and anti-inflammatory used for headaches, back pain, and muscle pain.",
    image: "/Products/brufen.jpeg",
    isStrip: true,
    pieces: 40,
    stripsPerBox: 3,
    topProduct: true,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 105,
    name: "Voltaren",
    price: 30,
    desc: "Voltaren contains Diclofenac Sodium, used to relieve pain and inflammation, especially in joint diseases and rheumatism.",
    image: "/Products/voltareen.png",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    topProduct: true,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 106,
    name: "Comtrex",
    price: 34,
    desc: "Comtrex is used to treat cold symptoms like nasal congestion, headache, fever, and sneezing.",
    image: "/Products/Comtrex.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 107,
    name: "Flurest",
    price: 22,
    desc: "Flurest is used to relieve cold symptoms like runny nose, sinus congestion, and fever.",
    image: "/Products/Flurest.jpeg",
    isStrip: true,
    pieces: 20,
    topProduct: true,
    stripsPerBox: 2,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 108,
    name: "Congestal",
    price: 28,
    desc: "Congestal treats colds, nasal congestion, cough, and fever.",
    image: "/Products/Congestal.jpeg",
    isStrip: true,
    pieces: 24,
    topProduct: true,
    stripsPerBox: 2,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 110,
    name: "Mucosol",
    price: 40,
    desc: "Mucosol is a mucus dissolver used to treat cough with phlegm in respiratory tract diseases.",
    image: "/Products/Mucosol.jpeg",
    isStrip: false,
    pieces: 50,
    stripsPerBox: 0,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 111,
    name: "Sinupret",
    price: 65,
    desc: "Sinupret is a herbal supplement that helps treat sinus infections and congestion.",
    image: "/Products/Sinupret.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 112,
    name: "Oplex",
    price: 25,
    desc: "Oplex syrup is used to treat cough and expel phlegm.",
    image: "/Products/Oplex.jpeg",
    isStrip: false,
    pieces: 40,
    stripsPerBox: 0,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 113,
    name: "Tussivan",
    price: 30,
    desc: "Tussivan is used to treat dry cough.",
    image: "/Products/Tussivan.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 2,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 114,
    name: "Amoxil",
    price: 42,
    desc: "Amoxil contains Amoxicillin, a broad-spectrum antibiotic used to treat respiratory tract infections.",
    image: "/Products/Amoxil.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 115,
    name: "Curam",
    price: 55,
    desc: "Curam contains Amoxicillin and Clavulanic Acid, used to treat sinus infections.",
    image: "/Products/Curam.jpeg",
    isStrip: true,
    topProduct: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 116,
    name: "Augmentin",
    price: 60,
    desc: "Augmentin contains Amoxicillin and Clavulanate, a broad-spectrum antibiotic.",
    image: "/Products/Augmentin.jpeg",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 117,
    name: "Zithromax",
    price: 70,
    desc: "Zithromax contains Azithromycin, an antibiotic used to treat throat, lung, and ear infections.",
    image: "/Products/Zithromax.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 118,
    name: "Cefotax",
    price: 90,
    desc: "Cefotax is a cephalosporin antibiotic used for severe infections.",
    image: "/Products/Cefotax.jpeg",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 119,
    name: "Septrin",
    price: 33,
    desc: "Septrin contains Sulfamethoxazole and Trimethoprim, used to treat urinary and respiratory infections.",
    image: "/Products/Septrin.jpeg",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 120,
    name: "Tavanic",
    price: 80,
    desc: "Tavanic contains Levofloxacin, a strong antibiotic used to treat respiratory tract infections.",
    image: "/Products/Tavanic.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 121,
    name: "Feroglobin",
    price: 50,
    desc: "Feroglobin contains Iron, Vitamin B12, and Folic Acid, used to treat anemia cases.",
    image: "/Products/Feroglobin.jpeg",
    isStrip: false,
    pieces: 30,
    topProduct: true,
    stripsPerBox: 0,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 122,
    name: "Multi-Maca",
    price: 85,
    desc: "Multi-Maca is a natural dietary supplement used to improve energy and sexual performance.",
    image: "/Products/Multi-Maca.jpeg",
    isStrip: false,
    pieces: 25,
    topProduct: true,
    stripsPerBox: 0,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 123,
    name: "Hematinic",
    price: 35,
    desc: "Hematinic is a formula for treating anemia containing Iron, Folic Acid, and B vitamins.",
    image: "/Products/Hematinic.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 124,
    name: "Feromin",
    price: 32,
    desc: "Feromin is an Iron and multivitamin-rich dietary supplement used to treat anemia and mineral deficiency.",
    image: "/Products/Feromin.jpeg",
    isStrip: true,
    pieces: 20,
    topProduct: true,
    stripsPerBox: 2,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 125,
    name: "Becozyme",
    price: 28,
    desc: "Becozyme contains B complex vitamins, used to treat nerve weakness and fatigue.",
    image: "/Products/Becozyme.jpeg",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 126,
    name: "Amaryl",
    price: 45,
    desc: "Amaryl contains Glimepiride, used to stimulate the pancreas to secrete insulin in diabetic patients.",
    image: "/Products/Amaryl.jpeg",
    isStrip: true,
    pieces: 30,
    topProduct: true,
    stripsPerBox: 2,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 127,
    name: "Janumet",
    price: 140,
    desc: "Janumet contains Metformin and Sitagliptin, used to regulate blood sugar levels.",
    image: "/Products/Janumet.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 128,
    name: "Cidophage",
    price: 30,
    desc: "Cidophage contains Metformin, used for Type 2 diabetes and sometimes for polycystic ovary cases.",
    image: "/Products/Cidophage.jpeg",
    isStrip: true,
    pieces: 20,
    topProduct: true,
    stripsPerBox: 2,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 129,
    name: "Glucophage",
    price: 36,
    desc: "Glucophage is the brand name for Metformin, which works by reducing glucose production in the liver.",
    image: "/Products/Glucophage.jpeg",
    isStrip: true,
    pieces: 25,
    topProduct: true,
    stripsPerBox: 2,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 130,
    name: "Mixtard",
    price: 95,
    desc: "Mixtard is an intermediate-acting insulin used to control blood sugar levels in diabetic patients.",
    image: "/Products/Mixtard.jpeg",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 132,
    name: "Amlodipine",
    price: 28,
    desc: "Amlodipine is a calcium channel blocker used to reduce blood pressure and improve blood flow.",
    image: "/Products/Amlodipine.jpeg",
    isStrip: true,
    pieces: 25,
    topProduct: true,
    stripsPerBox: 2,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 133,
    name: "Capoten",
    price: 33,
    desc: "Capoten contains Captopril, an ACE inhibitor used to treat high blood pressure.",
    image: "/Products/Capoten.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 134,
    name: "Norvasc",
    price: 31,
    desc: "Norvasc contains Amlodipine, used to reduce blood pressure and prevent angina.",
    image: "/Products/Norvasc.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 135,
    name: "Tenormin",
    price: 37,
    desc: "Tenormin contains Atenolol, a beta-blocker medication used for high blood pressure and angina.",
    image: "/Products/Tenormin.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 136,
    name: "Tryptizol",
    price: 40,
    desc: "Tryptizol contains Amitriptyline, a tricyclic antidepressant that helps calm nerves.",
    image: "/Products/Tryptizol.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 137,
    name: "Stugeron",
    price: 18,
    desc: "Stugeron contains Cinnarizine, used to treat dizziness, vertigo, and motion sickness.",
    image: "/Products/Stugeron.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 138,
    name: "Dogmatil",
    price: 26,
    desc: "Dogmatil contains Sulpiride, used to treat anxiety, irritable bowel syndrome, and some psychological disorders.",
    image: "/Products/Dogmatil.jpeg",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 139,
    name: "Cerebrolysin",
    price: 150,
    desc: "Cerebrolysin is an injectable solution to improve brain function in cases of stroke or Alzheimer's.",
    image: "/Products/Cerebrolysin.jpeg",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 140,
    name: "Lyrica",
    price: 120,
    desc: "Lyrica contains Pregabalin, used to treat nerve inflammation, muscle pain, and general anxiety.",
    image: "/Products/Lyrica.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 141,
    name: "Orohex",
    price: 22,
    desc: "Orohex is a mouthwash containing Chlorhexidine, used to treat gum inflammation and mouth ulcers.",
    image: "/Products/Orohex.jpeg",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 142,
    name: "Mycozal",
    price: 19,
    desc: "Mycozal oral gel contains Miconazole, an antifungal used to treat mouth and tongue fungi.",
    image: "/Products/Mycozal.jpeg",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 143,
    name: "Decal B12",
    price: 35,
    desc: "Decal B12 supplement contains Vitamin B12 and Calcium, used to treat mouth ulcers.",
    image: "/Products/Decal B12.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "first-aid",
    IsRoshetta: false,
  },
  {
    id: 146,
    name: "Bepanthen",
    price: 38,
    desc: "Bepanthen cream is used to moisturize skin and treat irritation and dryness.",
    image: "/Products/paramol.jpeg",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    topProduct: false,
    category: "skin-care",
    IsRoshetta: false,
  },
  {
    id: 147,
    name: "Fucidin",
    price: 44,
    desc: "Fucidin is an antibiotic ointment used to treat skin infections and inflamed wounds.",
    image: "/Products/paramol.jpeg",
    isStrip: false,
    topProduct: true,
    pieces: 30,
    stripsPerBox: 0,
    category: "skin-care",
    IsRoshetta: false,
  },
  {
    id: 148,
    name: "MEBO",
    price: 55,
    desc: "MEBO is a natural ointment containing Beta-Sitosterol, used to treat burns and superficial wounds.",
    image: "/Products/paramol.jpeg",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    topProduct: false,
    category: "skin-care",
    IsRoshetta: false,
  },
  {
    id: 149,
    name: "Dermoviva",
    price: 25,
    desc: "Dermoviva cream contains natural ingredients like olive oil and aloe vera, used to moisturize skin.",
    image: "/Products/paramol.jpeg",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    topProduct: false,
    category: "skin-care",
    IsRoshetta: false,
  },
  {
    id: 150,
    name: "Solpadeine",
    price: 36,
    desc: "Solpadeine is a fast-acting pain reliever that contains paracetamol, codeine, and caffeine.",
    image: "/Products/Solpadeine.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 154,
    name: "Actifed",
    price: 30,
    desc: "Actifed is a combination medication used to relieve symptoms of allergy, hay fever, and the common cold.",
    image: "/Products/Actifed.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 155,
    name: "Xyzal",
    price: 42,
    desc: "Xyzal (levocetirizine) is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.",
    image: "/Products/Xyzal.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 158,
    name: "Forxiga",
    price: 125,
    desc: "Forxiga (dapagliflozin) is an SGLT2 inhibitor used in the management of type 2 diabetes.",
    image: "/Products/Forxiga.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 159,
    name: "Tilcotil",
    price: 48,
    desc: "Tilcotil (tenoxicam) is a nonsteroidal anti-inflammatory drug (NSAID) used to relieve inflammation and pain associated with musculoskeletal disorders.",
    image: "/Products/Tilcotil.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 160,
    name: "Naproxen",
    price: 37,
    desc: "Naproxen is a commonly used NSAID for the treatment of pain, fever, and inflammation.",
    image: "/Products/Naproxen.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 161,
    name: "Declophen",
    price: 33,
    desc: "Declophen (diclofenac sodium) is used to relieve pain and inflammation in conditions such as rheumatoid arthritis.",
    image: "/Products/Declophen.jpeg",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 163,
    name: "Otrivin",
    price: 26,
    desc: "Otrivin is a nasal decongestant spray that provides fast relief from nasal congestion due to colds, sinusitis, or allergies.",
    image: "/Products/Otrivin.jpeg",
    isStrip: false,
    pieces: 1,
    stripsPerBox: 0,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 164,
    name: "Zyrtec",
    price: 38,
    desc: "Zyrtec (cetirizine) is a second-generation antihistamine that treats hay fever, allergic rhinitis, and hives.",
    image: "/Products/Zyrtec.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 165,
    name: "Glimepiride",
    price: 44,
    desc: "Glimepiride is an oral diabetes medication that helps the pancreas produce insulin.",
    image: "/Products/Glimepiride.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 166,
    name: "Jardiance",
    price: 130,
    desc: "Jardiance (empagliflozin) is a prescription medicine used to lower blood sugar in adults with type 2 diabetes.",
    image: "/Products/Jardiance.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 167,
    name: "Victoza",
    price: 160,
    desc: "Victoza (liraglutide) is an injectable medication used to improve blood sugar control in adults with type 2 diabetes.",
    image: "/Products/Victoza.jpeg",
    isStrip: false,
    pieces: 1,
    stripsPerBox: 0,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: true,
  },
  {
    id: 168,
    name: "Olfen",
    price: 39,
    desc: "Olfen (diclofenac potassium) is a fast-acting painkiller used to relieve acute pain, such as dental pain, joint pain, and muscular pain.",
    image: "/Products/Olfen.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 169,
    name: "Adol",
    price: 22,
    desc: "Adol (paracetamol) is a commonly used analgesic and antipyretic for the treatment of mild to moderate pain and fever.",
    image: "/Products/Adol.jpeg",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 170,
    name: "Feldene",
    price: 43,
    desc: "Feldene (piroxicam) is a nonsteroidal anti-inflammatory drug (NSAID) used to relieve symptoms of rheumatoid arthritis and osteoarthritis.",
    image: "/Products/Feldene.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 171,
    name: "Piriton",
    price: 27,
    desc: "Piriton (chlorpheniramine) is an antihistamine used to relieve allergy symptoms such as runny nose, itchy eyes, sneezing, and skin rashes.",
    image: "/Products/Piriton.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 172,
    name: "Loratadine",
    price: 35,
    desc: "Loratadine is a non-drowsy antihistamine used to relieve symptoms of allergic rhinitis and urticaria (hives).",
    image: "/Products/Loratadine.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 173,
    name: "Antinal + Cold Relief",
    price: 32,
    desc: "This combination therapy includes Antinal (nifuroxazide) for gastrointestinal infections and a cold relief formula.",
    image: "/Products/Antinal + Cold Relief.jpeg",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 2,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 175,
    name: "Trajenta",
    price: 115,
    desc: "Trajenta (linagliptin) is an oral diabetes medicine that helps control blood sugar levels in adults with type 2 diabetes.",
    image: "/Products/Trajenta.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 177,
    name: "Tramadol",
    price: 58,
    desc: "Tramadol is a prescription opioid pain medication used to treat moderate to moderately severe pain.",
    image: "/Products/Tramadol.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: true,
  },
  {
    id: 178,
    name: "Catafast",
    price: 36,
    desc: "Catafast (diclofenac potassium) is a fast-dissolving painkiller used to relieve pain and inflammation.",
    image: "/Products/Catafast.jpeg",
    isStrip: true,
    pieces: 10,
    stripsPerBox: 1,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 179,
    name: "Norgesic",
    price: 40,
    desc: "Norgesic is a muscle relaxant and pain reliever that contains orphenadrine and paracetamol.",
    image: "/Products/Norgesic.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 181,
    name: "Fludrex",
    price: 34,
    desc: "Fludrex is a multi-symptom cold and flu reliever that contains paracetamol, pseudoephedrine, and chlorpheniramine.",
    image: "/Products/Fludrex.jpeg",
    isStrip: true,
    pieces: 20,
    topProduct: true,
    stripsPerBox: 2,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 183,
    name: "Insulatard",
    price: 105,
    desc: "Insulatard is an intermediate-acting insulin that provides blood sugar control for patients with diabetes.",
    image: "/Products/Insulatard.jpeg",
    isStrip: false,
    pieces: 1,
    stripsPerBox: 0,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 184,
    name: "Glucovance",
    price: 70,
    desc: "Glucovance is a combination of glyburide and metformin. It helps lower blood sugar in adults with type 2 diabetes.",
    image: "/Products/Glucovance.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 185,
    name: "Xigduo",
    price: 135,
    desc: "Xigduo is a combination of dapagliflozin and metformin, used in the management of type 2 diabetes.",
    image: "/Products/Xigduo.jpeg",
    isStrip: true,
    pieces: 28,
    stripsPerBox: 2,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 186,
    name: "Arcoxia",
    price: 88,
    desc: "Arcoxia (etoricoxib) is a selective COX-2 inhibitor used to treat various forms of arthritis.",
    image: "/Products/Arcoxia.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 187,
    name: "Mobitil",
    price: 44,
    desc: "Mobitil (meloxicam) is a nonsteroidal anti-inflammatory drug (NSAID) used to relieve the symptoms of joint disorders.",
    image: "/Products/Mobitil.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 188,
    name: "Neuroton",
    price: 60,
    desc: "Neuroton is a vitamin B-complex supplement used for treating peripheral neuropathy, muscle cramps, and nerve pain.",
    image: "/Products/Neuroton.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 192,
    name: "Amaryl M",
    price: 78,
    desc: "Amaryl M is a combination of glimepiride and metformin, prescribed to patients with type 2 diabetes.",
    image: "/Products/Amaryl M.jpeg",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: false,
  },
  {
    id: 193,
    name: "Ryzodeg",
    price: 145,
    desc: "Ryzodeg is a modern insulin combination of insulin degludec and insulin aspart.",
    image: "/Products/Ryzodeg.jpeg",
    isStrip: false,
    pieces: 1,
    stripsPerBox: 0,
    topProduct: false,
    category: "diabetes-care",
    IsRoshetta: true,
  },
  {
    id: 195,
    name: "Naprosyn",
    price: 50,
    desc: "Naprosyn (naproxen) is a nonsteroidal anti-inflammatory drug (NSAID) used to treat pain and inflammation.",
    image: "/Products/Naprosyn.png",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 197,
    name: "Myogesic",
    price: 41,
    desc: "Myogesic combines a muscle relaxant and an analgesic to relieve pain and muscle spasms.",
    image: "/Products/Myogesic.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "pain-relief",
    IsRoshetta: false,
  },
  {
    id: 199,
    name: "Rinofed",
    price: 29,
    desc: "Rinofed is an antihistamine and decongestant combination used to treat nasal congestion.",
    image: "/Products/Rinofed.jpeg",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
  {
    id: 200,
    name: "Solpadeine Cold",
    price: 40,
    desc: "Solpadeine Cold provides fast relief from cold and flu symptoms.",
    image: "/Products/Solpadeine Cold.jpeg",
    isStrip: true,
    pieces: 16,
    stripsPerBox: 2,
    topProduct: false,
    category: "cold-and-flu",
    IsRoshetta: false,
  },
];

export default data;
