const data = [
  {
    id: 101,
    name: "Panadol",
    price: 24,
    desc: "بانادول يحتوي على باراسيتامول، يُستخدم كمسكن للألم وخافض للحرارة في حالات الصداع، ألم الأسنان، الحمى، وآلام العضلات.",
    image: "",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 3,
    category: "pain-relief"
  },
  {
    id: 102,
    name: "Paramol",
    price: 20,
    desc: "بارامول يُستخدم لتسكين الألم وخفض الحرارة وعلاج أعراض نزلات البرد والإنفلونزا.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 2,
    category: "pain-relief"
  },
  {
    id: 103,
    name: "Cataflam",
    price: 38,
    desc: "كتافلام يحتوي على ديكلوفيناك بوتاسيوم، يُستخدم لعلاج آلام الأسنان، المفاصل، الصداع، وآلام الدورة الشهرية.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 4,
    category: "pain-relief"
  },
  {
    id: 104,
    name: "Brufen",
    price: 27,
    desc: "بروفين يحتوي على إيبوبروفين، مسكن للآلام ومضاد للالتهاب، يُستخدم في حالات الصداع، ألم الظهر، وآلام العضلات.",
    image: "",
    isStrip: true,
    pieces: 40,
    stripsPerBox: 3,
    category: "pain-relief"
  },
  {
    id: 105,
    name: "Voltaren",
    price: 30,
    desc: "فولتارين يحتوي على ديكلوفيناك صوديوم، يُستخدم لتخفيف الألم والالتهابات، خاصةً في أمراض المفاصل والروماتيزم.",
    image: "",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    category: "pain-relief"
  },
  {
    id: 106,
    name: "Comtrex",
    price: 34,
    desc: "كومتريكس يُستخدم لعلاج أعراض نزلات البرد مثل احتقان الأنف، الصداع، الحمى، والعطس.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "cold-and-flu"
  },
  {
    id: 107,
    name: "Flurest",
    price: 22,
    desc: "فلورست يُستخدم لتخفيف أعراض البرد مثل الرشح، احتقان الجيوب الأنفية، وارتفاع الحرارة.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "cold-and-flu"
  },
  {
    id: 108,
    name: "Congestal",
    price: 28,
    desc: "كونجستال يُعالج الزكام، احتقان الأنف، الكحة، والحرارة.",
    image: "",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 2,
    category: "cold-and-flu"
  },
  {
    id: 109,
    name: "Cold-Free",
    price: 18,
    desc: "كولد فري يُستخدم لعلاج أعراض البرد والأنفلونزا مثل الرشح والحمى والكحة الجافة.",
    image: "",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    category: "cold-and-flu"
  },
  {
    id: 110,
    name: "Mucosol",
    price: 40,
    desc: "ميوكوسول مذيب للبلغم يُستخدم لعلاج الكحة المصحوبة ببلغم في أمراض الجهاز التنفسي.",
    image: "",
    isStrip: false,
    pieces: 50,
    stripsPerBox: 0,
    category: "cold-and-flu"
  },
  {
    id: 111,
    name: "Sinupret",
    price: 65,
    desc: "سينيوبريت مكمل عشبي يُساعد في علاج التهابات الجيوب الأنفية والاحتقان.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "cold-and-flu"
  },
  {
    id: 112,
    name: "Oplex",
    price: 25,
    desc: "أوبلكس شراب يُستخدم لعلاج الكحة وطرد البلغم.",
    image: "",
    isStrip: false,
    pieces: 40,
    stripsPerBox: 0,
    category: "cold-and-flu"
  },
  {
    id: 113,
    name: "Tussivan",
    price: 30,
    desc: "توسيفان يُستخدم لعلاج السعال الجاف.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 2,
    category: "cold-and-flu"
  },
  {
    id: 114,
    name: "Amoxil",
    price: 42,
    desc: "أموكسيل يحتوي على أموكسيسيللين، مضاد حيوي واسع المدى يُستخدم لعلاج التهابات الجهاز التنفسي.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 115,
    name: "Curam",
    price: 55,
    desc: "كيورام يحتوي على أموكسيسيللين وكلافيولانيك أسيد، يُستخدم لعلاج التهابات الجيوب الأنفية.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 116,
    name: "Augmentin",
    price: 60,
    desc: "أوجمنتين يحتوي على أموكسيسيللين وكلافيولانات، مضاد حيوي واسع المدى.",
    image: "",
    isStrip: true,
    pieces: 24,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 117,
    name: "Zithromax",
    price: 70,
    desc: "زيثروماكس يحتوي على أزيثرومايسين، مضاد حيوي يُستخدم لعلاج التهابات الحلق، الرئة، الأذن.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 118,
    name: "Cefotax",
    price: 90,
    desc: "سيفوتاكس هو مضاد حيوي من نوع السيفالوسبورينات، يُستخدم في حالات العدوى الشديدة.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 119,
    name: "Septrin",
    price: 33,
    desc: "سبترين يحتوي على سلفاميثوكسازول وتريميثوبريم، يُستخدم لعلاج التهابات البول والجهاز التنفسي.",
    image: "",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 120,
    name: "Tavanic",
    price: 80,
    desc: "تافانيك يحتوي على ليفوفلوكساسين، مضاد حيوي قوي يُستخدم لعلاج التهابات الجهاز التنفسي.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 121,
    name: "Feroglobin",
    price: 50,
    desc: "فيروجلوبين يحتوي على الحديد وفيتامين ب12 وحمض الفوليك، يُستخدم لعلاج حالات الأنيميا.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 122,
    name: "Multi-Maca",
    price: 85,
    desc: "مالتي ماكا مكمل غذائي طبيعي يُستخدم لتحسين الطاقة والقدرة الجنسية.",
    image: "",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 123,
    name: "Hematinic",
    price: 35,
    desc: "هيماتينيك تركيبة لعلاج الأنيميا تحتوي على الحديد، حمض الفوليك، وفيتامينات ب.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 124,
    name: "Feromin",
    price: 32,
    desc: "فيرومين مكمل غذائي غني بالحديد وفيتامينات متعددة يُستخدم لعلاج الأنيميا ونقص المعادن.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 125,
    name: "Becozyme",
    price: 28,
    desc: "بيكوزيم يحتوي على مجموعة فيتامينات ب المركبة، يُستخدم لعلاج ضعف الأعصاب والإجهاد.",
    image: "",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 126,
    name: "Amaryl",
    price: 45,
    desc: "أمارييل يحتوي على جليمبريد، يُستخدم لتحفيز البنكرياس لإفراز الإنسولين في مرضى السكري.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 2,
    category: "diabetes-care"
  },
  {
    id: 127,
    name: "Janumet",
    price: 140,
    desc: "جانومت يحتوي على ميتفورمين وسيتاجليبتين، يُستخدم لتنظيم مستوى السكر في الدم.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "diabetes-care"
  },
  {
    id: 128,
    name: "Cidophage",
    price: 30,
    desc: "سيدوفاج يحتوي على ميتفورمين، يُستخدم في حالات السكري النوع الثاني، وأحيانًا لحالات تكيّس المبايض.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "diabetes-care"
  },
  {
    id: 129,
    name: "Glucophage",
    price: 36,
    desc: "جلوكوفاج هو الاسم التجاري للميتفورمين، ويعمل على تقليل إنتاج الجلوكوز من الكبد.",
    image: "",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    category: "diabetes-care"
  },
  {
    id: 130,
    name: "Mixtard",
    price: 95,
    desc: "ميكستارد هو إنسولين متوسط المفعول يُستخدم في التحكم في مستويات السكر في الدم لمرضى السكري.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "diabetes-care"
  },
  {
    id: 131,
    name: "Concor",
    price: 42,
    desc: "كونكور يحتوي على بيسوبرولول، من أدوية حاصرات بيتا، يُستخدم لعلاج ارتفاع ضغط الدم.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 132,
    name: "Amlodipine",
    price: 28,
    desc: "أملوديبين من مجموعة حاصرات قنوات الكالسيوم، يُستخدم لتقليل ضغط الدم وتحسين تدفق الدم.",
    image: "",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 133,
    name: "Capoten",
    price: 33,
    desc: "كابوتين يحتوي على كابتوبريل، من مثبطات الإنزيم المحول للأنجيوتنسين (ACEI)، يُستخدم لعلاج الضغط.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 134,
    name: "Norvasc",
    price: 31,
    desc: "نورفاسك يحتوي على أملوديبين، يُستخدم لتقليل ضغط الدم ومنع الذبحات الصدرية.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 135,
    name: "Tenormin",
    price: 37,
    desc: "تينورمين يحتوي على أتينولول، من أدوية حاصرات بيتا، يُستخدم في حالات الضغط والذبحة الصدرية.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 136,
    name: "Tryptizol",
    price: 40,
    desc: "تربتيزول يحتوي على أميتريبتيلين، يُستخدم كمضاد اكتئاب ثلاثي الحلقات، ويُساعد في تهدئة الأعصاب.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 137,
    name: "Stugeron",
    price: 18,
    desc: "ستوجيرون يحتوي على سيناريزين، يُستخدم لعلاج الدوخة، الدوار، ودوار الحركة.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 138,
    name: "Dogmatil",
    price: 26,
    desc: "دوجماتيل يحتوي على سلبيريد، يُستخدم لعلاج القلق والقولون العصبي وبعض الاضطرابات النفسية.",
    image: "",
    isStrip: true,
    pieces: 25,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 139,
    name: "Cerebrolysin",
    price: 150,
    desc: "سيريبروليزين هو محلول يُعطى بالحقن لتحسين وظائف المخ في حالات الجلطات الدماغية أو الزهايمر.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 140,
    name: "Lyrica",
    price: 120,
    desc: "ليركا يحتوي على بريجابالين، يُستخدم لعلاج التهابات الأعصاب، آلام العضلات، والقلق العام.",
    image: "",
    isStrip: true,
    pieces: 30,
    stripsPerBox: 3,
    category: "first-aid"
  },
  {
    id: 141,
    name: "Orohex",
    price: 22,
    desc: "اوراوهيكس غسول فم يحتوي على كلورهيكسيدين، يُستخدم لعلاج التهابات اللثة وقرح الفم.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 142,
    name: "Mycozal",
    price: 19,
    desc: "ميكوزال جل للفم يحتوي على ميكونازول، مضاد فطري يُستخدم لعلاج فطريات الفم واللسان.",
    image: "",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 143,
    name: "Decal B12",
    price: 35,
    desc: "ديكال بي 12 مكمل يحتوي على فيتامين B12 والكالسيوم، يُستخدم لعلاج تقرحات الفم.",
    image: "",
    isStrip: true,
    pieces: 20,
    stripsPerBox: 2,
    category: "first-aid"
  },
  {
    id: 144,
    name: "Betadine Mouthwash",
    price: 27,
    desc: "بيتادين غسول فم مطهر يحتوي على بوفيدون-يود، يُستخدم في حالات التهابات الفم واللثة.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 145,
    name: "Tantum Verde",
    price: 40,
    desc: "تانتم فيردي غسول فم مضاد للالتهاب ومسكن موضعي لآلام الحلق والتهابات الفم.",
    image: "",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    category: "first-aid"
  },
  {
    id: 146,
    name: "Bepanthen",
    price: 38,
    desc: "بانثينول كريم يُستخدم لترطيب الجلد وعلاج التسلخات والجفاف.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "skin-care"
  },
  {
    id: 147,
    name: "Fucidin",
    price: 44,
    desc: "فيوسيدين مرهم مضاد حيوي موضعي يُستخدم لعلاج العدوى الجلدية والجروح الملتهبة.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "skin-care"
  },
  {
    id: 148,
    name: "MEBO",
    price: 55,
    desc: "ميبو مرهم طبيعي يحتوي على بيتا سيتوستيرول، يُستخدم في علاج الحروق والجروح السطحية.",
    image: "",
    isStrip: false,
    pieces: 30,
    stripsPerBox: 0,
    category: "skin-care"
  },
  {
    id: 149,
    name: "Dermoviva",
    price: 25,
    desc: "ديرموفيفا كريم يحتوي على مكونات طبيعية مثل زيت الزيتون والألوفيرا، يُستخدم لترطيب البشرة.",
    image: "",
    isStrip: false,
    pieces: 25,
    stripsPerBox: 0,
    category: "skin-care"
  }
];

export default data;